### ISSUE TITLE
Does this work on Advantech DAQ cards?

### ISSUE THREAD

**Issue by AmirAliVz** [petebachant/daqmx#13]
Hello,
I want to ask if your code can also work on Advantech devices. I have a USB-4711A and I can't find any code or library to read data using Python. I appreciate it if you share your experience with me.
Thank you in advance

**Comment by petebachant** [comment]
I would doubt it, but I'm not sure. Do they provide a C library?

**Comment by AmirAliVz** [comment]
Yes, the SDK provides examples in various programming languages including C++. but it doesn't have anything for python. I found a library for NI devices, its name is nidaqmx but nothing for Advantech.

**Comment by petebachant** [comment]
Ah, I see. You could probably use a similar approach using the `ctypes` module to wrap their C library.

**Comment by AmirAliVz** [comment]
Yes, that's the right approach. 
But I've just found out that the latest version SDK and driver can also support Python
Thank you

**Comment by petebachant** [comment]
Glad to hear it!

**Comment by cancertataje** [comment]
Hello,
I am trying to take readings from a USB-4711A with python but I have not been successful yet, could you tell me how you did it?
