### ISSUE TITLE
synch_ai_ao.py 

### ISSUE THREAD

**Issue by eadkins333** [petebachant/daqmx#7]
Hello, 

I am having an issue with the AO Sample clock part of the example.  I keep getting the RuntimeError: Requested value is not a supported value for this property.   Any suggestions?

daqmx.CfgSampClkTiming(AOtaskHandle, "", sr/2, daqmx.Val_Rising, 
                       daqmx.Val_ContSamps, buffsize)

**Comment by petebachant** [comment]
@eadkins333, did you get this working okay? Did any code inside the package need to be changed?

**Comment by eadkins333** [comment]
Sorry I should have posted this.  The unit we were using (USB6009) was too
slow and didn't support continuous AO output.

**Comment by petebachant** [comment]
No worries. Glad you figured it out.
